# used for local development:
#   docker-compose up -d
#   iex -S mix

version: '3.3'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./data/postgres:/data
    ports:
      - 5432:5432
    environment:
      LANG: en_US.utf8
      PGDATA: /data
      POSTGRES_DB: geo_tasks_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
